#!/bin/bash
#This shebang is for synax only. Do not make executable!

myborg_export () { key=$1; shift; export $key="$*"; }

myborg_export MYBORG_INDEX        ~/.local/var/myborg/current.txt
myborg_export MYBORG              $(cat ${MYBORG_INDEX})
myborg_export BORG                ${MYBORG}/submodules/borg
myborg_export MYBORG_SUBMODULES   ${MYBORG}/submodules
myborg_export MYBORG_DOTFILES     ${MYBORG}/dots

myborg_log () {
    echo $* >> ~/.myborg.log
    [ -f ~/.myborg.flag.verbose ] && echo $*
}

myborg_source () {
    myborg_log ++ source [${1}]
        [ ! -d ${1} ] && source ${1}
        [   -d ${1} ] && {
            for name in $(/bin/ls ${1} | grep ^[0-9] | sort); do 
              myborg_source ${1}/${name}; 
            done
        }
    myborg_log -- source [${1}]
}

myborg_source_all () {
    myborg_log SOURCING ALL
    myborg_source ${MYBORG_SUBMODULES}
}

[ ! "$1" == "" ] && {
    myborg_export PATH ${PATH}:${BORG}/bin
    myborg_source borg:__first__
    myborg_source ${MYBORG_DOTFILES}/dot$1
    myborg_source borg:__last__
    source borg:path:clean
}
