#!/source/this/sh
__myborg_borgify () {
    [ "$1" == "" ] && return
    . myborg_source borg:__first__
    . myborg_source ${MYBORG_DOTS}/dot$1
    . myborg_source borg:__last__
    . myborg_source borg:path:clean
}


