#!/usr/bin/env bash

[ ! "$0" == "./install" ] && {
    echo "try './install'"
    exit
}

source ${PWD}/main; echo "was: [${MYBORG}]"

echo ${PWD} > ${MYBORG_INDEX}

source ${PWD}/main; echo "now: [${MYBORG}]"

source ${PWD}/index
