#!/source/this/sh

export MYBORG=$(cat ~/.local/var/myborg/current.txt)
export MYBORG_BIN=${HOME}/.local/var/myborg/mybin
export MYBORG_MODS=${MYBORG}/.mods
export MYBORG_DOTS=${MYBORG}/dots
export PATH=${PATH}:${HOME}/.local/bin
export PATH=${PATH}:${MYBORG}/bin
export PATH=${PATH}:${MYBORG}/borgbin
export PYTHONPATH=${MYBORG}/lib

main () {
    echo "++[$MYBORG/main] $*"
    echo processing index...   ; __myborg__.load-index
    echo activating mods...    ; __myborg_activate__
    echo borgifying...         ; __myborg_borgify__ $1
    echo "++[$MYBORG/main] $*"
}

red     () { printf "$(tput bold)$(tput setaf 15)$(tput setab 1)$1$(tput sgr0)" ; }
green   () { printf "$(tput bold)$(tput setaf 15)$(tput setab 2)$1$(tput sgr0)" ; }
yellow  () { printf "$(tput bold)$(tput setaf 15)$(tput setab 3)$1$(tput sgr0)" ; }
blue    () { printf "$(tput bold)$(tput setaf 15)$(tput setab 4)$1$(tput sgr0)" ; }
ok      () { printf "$(tput bold)$(tput setaf 2)$(tput setab 15)$1$(tput sgr0)" ; }

__myborg_source__ () {
    [ "$1" = "-q" ] || __myborg__.note sourcing $*
    [ "$1" = "-q" ] && shift
    source $*
}
__myborg_borgify__ () {
    # THIS RELIES ON BORG MODULE LOADED AND ACTIVATED.
    [ ! "$1" == "" ] && {
         __myborg_source__ borg:__first__
        __myborg_source__ ${MYBORG_DOTS}/dot$1
        __myborg_source__ borg:__last__
        __myborg_source__ borg:path:clean
    }
}
__myborg_activate__ () {
    for name in $(ls ${MYBORG_MODS} | grep "\d.*"); do
        path=${MYBORG_MODS}/$name
        [ -f ${path}/.insitu/activate ] || {
            printf "[skip] \t[$name]\n"
            continue
        }
        printf "[ ok ] \t[$name]\n"
        > /dev/null 2>/dev/null     pushd $path/.insitu
        . ./activate
        > /dev/null 2>/dev/null     popd
    done
}

main $*
