#!/bin/sh
echo cloning to MODS ...
x () { myborg-clone-to ${MYBORG_MODS}/$* ; }
x 100.lbin.pylib.bch.iter     git@github.com:bryanhann/lbin.pylib.bch.itertools
x 140.lbin.bch.here           git@github.com:bryanhann/lbin.bch.here
x 150.lbin.bch.misc           git@github.com:bryanhann/lbin.bch.misc
x 160.lbin.bch.poet           git@github.com:bryanhann/lbin.bch.poet
x 200.lbin.bch.borgtry        git@github.com:bryanhann/lbin.bch.borgtry
x 210.lbin.bch.mnt            git@github.com:bryanhann/lbin.bch.mnt
x 220.lbin.bch.zot            git@github.com:bryanhann/lbin.bch.zot
x 230.lbin.bch.ws852          git@github.com:bryanhann/lbin.bch.ws852 -b insitu
x 240.lbin.bch.vjot           git@github.com:bryanhann/lbin.bch.vjot
x 250.lbin.bch.zjot           git@github.com:bryanhann/lbin.bch.zjot
x 260.lbin.bch.ec2            git@github.com:bryanhann/lbin.bch.ec2   -b lbin
x 270.lbin.bch.popo           git@github.com:bryanhann/lbin.bch.popo  -b lbin
x 280.lbin.bch.poetry         git@github.com:bryanhann/lbin.bch.poetry
x 290.lbin.bch.monty          git@github.com:bryanhann/lbin.bch.monty
x 300.lbin.bch.plate          git@github.com:bryanhann/lbin.bch.plate
x 800.bchp.history.data       git@github.com:bryanhann/bchp.history.data
x 810.bchp.history.control    git@github.com:bryanhann/bchp.history.control
x 900.bch.misc                git@github.com:bryanhann/myborg.900.bch-misc
#x 320.mydts                   git@github.com:bryanhann/myborg.320.mydts
#x 330.mycmd                   git@github.com:bryanhann/myborg.330.mycmd
#x 820.popo                    git@github.com:bryanhann/myborg.995.popo
#x 100.bchk                    git@github.com:bryanhann/bchk.__base__
