#!/bin/sh
cloneto () { [ -d $1 ]||{ D=$1;shift;mkdir -p $(dirname $D);git clone $* ${D}; echo; }; }
v () { cloneto ${MYBORG_VENDOR}/$* ; }
x () { cloneto ${MYBORG_MODS}/$* ; }

BCH=git@github.com:bryanhann

#echo cloning to VENDOR ...

v bats/bats-core     https://github.com/bats-core/bats-core.git
v bats/bats-support  https://github.com/bats-core/bats-support.git
v bats/bats-assert   https://github.com/bats-core/bats-assert.git

#echo cloning to MODS ...

x 100.lbin.pylib.bch.iter     ${BCH}/lbin.pylib.bch.itertools
x 140.lbin.bch.here           ${BCH}/lbin.bch.here
x 150.lbin.bch.misc           ${BCH}/lbin.bch.misc
x 151.lbin.bch.hansel         ${BCH}/lbin.bch.hansel
x 160.lbin.bch.poet           ${BCH}/lbin.bch.poet
x 200.lbin.bch.borgtry        ${BCH}/lbin.bch.borgtry
x 210.lbin.bch.mnt            ${BCH}/lbin.bch.mnt
x 220.lbin.bch.zot            ${BCH}/lbin.bch.zot
x 230.lbin.bch.ws852          ${BCH}/lbin.bch.ws852 -b insitu
x 240.lbin.bch.vjot           ${BCH}/lbin.bch.vjot
x 250.lbin.bch.zjot           ${BCH}/lbin.bch.zjot
x 260.lbin.bch.ec2            ${BCH}/lbin.bch.ec2   -b lbin
x 270.lbin.bch.popo           ${BCH}/lbin.bch.popo  -b lbin
x 280.lbin.bch.poetry         ${BCH}/lbin.bch.poetry
x 290.lbin.bch.monty          ${BCH}/lbin.bch.monty
x 300.lbin.bch.plate          ${BCH}/lbin.bch.plate
x 800.bchp.history.data       ${BCH}/bchp.history.data
x 810.bchp.history.control    ${BCH}/bchp.history.control
x 900.bch.misc                ${BCH}/myborg.900.bch-misc
x 999.test.fred               ${BCH}/test.fred
