#!/bin/sh
x () { myborg-clone-to ${MYBORG_VENDOR}/$* ; }
x bats/bats-core     https://github.com/bats-core/bats-core.git
x bats/bats-support  https://github.com/bats-core/bats-support.git
x bats/bats-assert   https://github.com/bats-core/bats-assert.git

