#!/usr/bin/env python3

import sys
from pathlib import Path

USAGE="""
Usage:
    borg-find3-suffix SUFFIX

    Print the first path found that ends with SUFFIX.
    Search three levels deep staring from [/].
    Exit 0 if successful, 1 if not, 2 if SUFFIX not provided.
"""

def three_levels_walk():
    root=Path('/')
    for ii in root.glob('*'):
        yield ii
        for jj in ii.glob('*'):
            yield jj
            for kk in jj.glob('*'):
                yield kk


if __name__ == '__main__':
    suffix = (sys.argv[1:] + [''])[0]

    if suffix in ('', '-h', '--help'):
        print(USAGE)
        exit(2)

    for path in three_levels_walk():
        if str(path).endswith(suffix):
            print(path)
            exit(0)

    exit(1)
